config/routes.rb
Printersting::Application.routes.draw do
  resources :pins

 devise_for :users, controllers: { registrations: 'registrations' }
  root "pins#index"
  get "about" => "pages#about"

  

end

app/models/pin.rb
class Pin < ActiveRecord::Base
	belongs_to :user

	has_attached_file :image,
		:storage => :dropbox,
   		:dropbox_credentials => Rails.root.join("config/dropbox.yml"),
    	:styles => { :medium => "300x300>", :thumb => "100x100>" }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :pins
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home	
  end

    def about	
  end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  def index
    @pins = Pin.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 3)

  end

  def show
  end

  def new
    @pin = current_user.pins.build
  end

  def edit
  end

  def create
    @pin = current_user.pins.build(pin_params)

    respond_to do |format|
      if @pin.save
        format.html { redirect_to @pin, notice: 'Pin was successfully created.' }
        format.json { render action: 'show', status: :created, location: @pin }
      else
        format.html { render action: 'new' }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @pin.update(pin_params)
        format.html { redirect_to @pin, notice: 'Pin was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @pin.destroy
    respond_to do |format|
      format.html { redirect_to pins_url }
      format.json { head :no_content }
    end
  end

  private

    def set_pin
      @pin = Pin.find(params[:id])
    end

    def correct_user
      @pin = current_user.pins.find_by(id: params[:id])
      redirect_to pins_path, notice: "Not authorised to edit this pin" if @pin.nil?
    end  

    def pin_params
      params.require(:pin).permit(:description, :image)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
    def create
      if verify_recaptcha
        super
      else
        build_resource
        clean_up_passwords(resource)
        flash.now[:alert] = "There was an error with the recaptcha code below. Please re-enter the code."      
        flash.delete :recaptcha_error
        render :new
      end
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-static-top navbar-inverse navbar-default" role="navigation">
  <div class="container">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to "Pinteresting", root_path, class: "navbar-brand" %>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav navbar-right">
      <li>
        <%= link_to root_path do %>
           <span class="glyphicon glyphicon-home"></span> Home
        <% end %>   
      </li>
      <li>
        <%= link_to about_path do %>
          <span class="glyphicon glyphicon-info-sign"></span> About
        <% end %>  
      </li> 
      <% if user_signed_in? %>
          <li>
            <%= link_to edit_user_registration_path do %>
              <span class="glyphicon glyphicon-user"></span> Account
            <% end %>
          </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
               <span class="glyphicon glyphicon-pushpin"></span> Pins<b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li>
                  <%= link_to pins_path do %>
                    <span class="glyphicon glyphicon-eye-open"></span> View All
                  <% end %>  
                </li>
                <li>
                  <%= link_to new_pin_path do %>
                    <span class="glyphicon glyphicon-plus"></span> New Pin
                  <% end %>
                </li>
              </ul>
          </li>
          <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Sign in", new_user_session_path %></li>
       <% end %>   
    </ul>
  </div><!-- /.navbar-collapse -->
</div><!-- /.navbar-container -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Printersting</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
	<%= render 'layouts/header' %>
	<div class="container">
		<% flash.each do |name, msg| %>
     	<%= content_tag(:div, msg, class: "alert alert-info") %>
		<% end %>
		<%= yield %>
	</div>

</body>
</html>

app/views/pages/_home.html.erb
<div class="jumbotron center">
	<h1>Welcome to my app!</h1>
     <p>
       <%= link_to "Log in", new_user_session_path, class: "btn btn-default btn-lg" %>
       <%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary btn-lg" %>
 	 </p>    
</div>

app/views/pages/about.html.erb
<h1>About us</h1>
<p>We are working on our oneMonthRails Printersting app!</p>

app/views/pins/_form.html.erb
<%= form_for @pin, html: { multipart: true } do |f| %>
  <% if @pin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

      <ul>
      <% @pin.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="panel-body">
    <h4>
      <div class="label label-info">
        <%= f.label :description %>
      </div>
    </h4>
  <div class="field">
    <%= f.text_field :description, placeholder: "pin description", class: "form-control"%>
  </div>
  <div class="form-group">
    <h4>
      <div class="label label-info">
        <%= f.label :image %>
      </div>
    </h4>
    <%= f.file_field :image, class: "form-control" %>
  </div>
  <div class="actions">
    <br>
    <%= f.submit class: "btn btn-primary" %>
  </div>
 </div>
<% end %>

app/views/pins/edit.html.erb
<div class="panel panel-default">
	<div class="panel-heading">
		<h1>Edit pin</h1>
	</div>

	<%= render 'form' %>
	<br>
	<div class="panel-footer">
		<%= link_to 'Show', @pin %> |
		<%= link_to 'Back', pins_path %>
	</div>	
</div>

app/views/pins/index.html.erb
<%= render 'pages/home' unless user_signed_in? %>
<div id="pins" class="transitions-enabled">
      <% @pins.each do |pin| %>
        <div class="box panel panel-default">
          <%= image_tag pin.image.url(:thumb) if pin.image? %>
          <div class="panel-body"> 
            <%= pin.description %>
            <%= pin.user.email if pin.user %>
            <br>
            <%= link_to pin do %>
              <span class="glyphicon glyphicon-eye-open"></span>
            <% end %>  
              <% if pin.user == current_user %>
                <%= link_to edit_pin_path(pin) do %>
                  <span class="glyphicon glyphicon-edit"></span>
                <% end %>  
                <%= link_to pin, method: :delete, data: { confirm: 'Are you sure?' } do %>
                  <span class="glyphicon glyphicon-remove"></span>
                <% end %>  
              <% end %>
        </div>
      </div> 
    <% end %>

</div>
  <div class="center">
   <%= will_paginate @collection, renderer: BootstrapPagination::Rails %>
  </div> 

app/views/pins/new.html.erb
<div class="panel panel-default">
	<div class="panel-heading">
		<h1>New pin</h1>
	</div>
	<div class="form-group">
		<%= render 'form' %>
	</div>
	 <div class="panel-footer">
		<%= link_to 'Back', pins_path %>
	</div>
</div>

app/views/pins/show.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h1><%= @pin.description %></h1>
  </div>  
	<div class="panel-body">
		<p>
  			<%= image_tag @pin.image.url %>
		</p>
	</div>
	<div class="panel-footer">
		<% if @pin.user == current_user %>
		<%= link_to 'Edit', edit_pin_path(@pin) %> |
		<% end %>
		<%= link_to 'Back', pins_path %>
	</div>
</div>